---
name: xcop
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  xcop:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4
      - uses: g4s8/xcop-action@v1.3
